### ISSUE TITLE
Error : SendFailure

### ISSUE THREAD

**Issue by emresaracoglu** [thedillonb/RepoStumble#12]
Hello,

![c94732bb-9376-4d72-a213-1f9acd1ec108](https://user-images.githubusercontent.com/297968/36712870-88933142-1b93-11e8-92eb-2313d77f56c4.png)

Last 4-5 days I getting this error : 

Error: Send failure (Error writing headers)

**Comment by jtbrush56** [comment]
I am receiving this same error.

**Comment by grochadc** [comment]
Bump

**Comment by thedillonb** [comment]
I will fix this within the week. Should have an update in the iTunes store this weekend. Sorry for the delay.

**Comment by emresaracoglu** [comment]
Hi, any changes?

**Comment by thedillonb** [comment]
The changes are being reviewed by Apple as I type this. It usually takes a day so we should see it in the app store any time now.

**Comment by emresaracoglu** [comment]
Thank you for update!

**Comment by excalith** [comment]
Just to let everyone know: App is live on AppStore and the problem is gone! Thanks Dillon

**Comment by emresaracoglu** [comment]
#855d111b commit
