### ISSUE TITLE
Server 404

### ISSUE THREAD

**Issue by banzu** [thedillonb/RepoStumble#3]
When trying to search the list of languages under Add New Interest and when trying to view the Showcase tab, I get a 404 error from the server.

**Comment by sejgit** [comment]
Been getting this as well on both iPhone and iPad devices.

**Comment by thedillonb** [comment]
Wow, you're right. I'll get looking into this immediately! Thanks for pointing this out

**Comment by thedillonb** [comment]
This has been resolved! Should be affective immediately. Let me know if you see any further issue.

**Comment by sejgit** [comment]
You rock!  Confirmed. 

Stephen

**Comment by banzu** [comment]
Yep, double-confirmed. Quick work cap'n!
