### ISSUE TITLE
Opening Goverment Apps showcase fails

### ISSUE THREAD

**Issue by perryprog** [thedillonb/RepoStumble#9]
Steps to reproduce:
- Open RepoStumble
- Click showcase in the bottom right corner
- Scroll down until you see 'Goverment apps' for me it's the 3rd one down
- Click it

You should end up on a screen that is blank and has a dialog saying 'Object reference not set to an instance of an object.'

**Comment by thedillonb** [comment]
This has been resolved in the up coming release.
